services:
  postgres:
    image: postgres:17
    container_name: dealroom-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: theo
      POSTGRES_DB: dealroom

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
